"""
Django settings for lcshop project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from django.contrib.messages import constants as messages
from pathlib import Path
import socket
from decouple import config


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", cast=bool, default=False)

# --- Allowed hosts ---
ALLOWED_HOSTS = [
    h.strip()
    for h in config(
        "ALLOWED_HOSTS",
        default="localhost,127.0.0.1,.elasticbeanstalk.com,.amazonaws.com,.compute.internal",
    ).split(",")
    if h.strip()
]

fqdn = socket.gethostname()
short = fqdn.split(".")[0]

for h in (fqdn, short):
    if h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(h)

try:
    private_ip = socket.gethostbyname(socket.gethostname())
    if private_ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(private_ip)
except Exception:
    pass

# --- CSRF / Proxy ---
CSRF_TRUSTED_ORIGINS = [
    "https://*.elasticbeanstalk.com",
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# --- Apps ---
INSTALLED_APPS = [
    "admin_honeypot",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "category",
    "accounts",
    "store",
    "carts",
    "orders",
    "storages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_session_timeout.middleware.SessionTimeoutMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SESSION_EXPIRE_SECONDS = 3600
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = "login"

ROOT_URLCONF = "lcshop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "category.context_processors.category_items",
                "carts.context_processor.counter",
            ],
        },
    },
]

WSGI_APPLICATION = "lcshop.wsgi.application"
AUTH_USER_MODEL = "accounts.Account"

# --- Database (NOTE: SQLite is not production-safe on EB; move to RDS next) ---
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- Internationalization ---
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ==============================
# STATIC & MEDIA FILES (S3)
# ==============================

AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-west-2")

# Static bucket (must be set in EB env vars)
AWS_STORAGE_BUCKET_NAME_STATIC = config("AWS_STORAGE_BUCKET_NAME_STATIC", default="").strip()

# Media bucket (uploads)
AWS_MEDIA_BUCKET_NAME = config("AWS_MEDIA_BUCKET_NAME", default="lcshop-media-prod").strip()

USE_S3_STATIC = bool(AWS_STORAGE_BUCKET_NAME_STATIC)
USE_S3_MEDIA = bool(AWS_MEDIA_BUCKET_NAME)

# IMPORTANT: your buckets have ACLs disabled (Bucket owner enforced)
# So we must NOT send any ACL headers.
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {}  # ✅ prevents AccessControlListNotSupported

# Local static setup (for dev)
STATICFILES_DIRS = [
    BASE_DIR / "lcshop" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

if USE_S3_STATIC:
    AWS_LOCATION = "static"

    # ✅ Make sure django-storages has the standard bucket variable too
    AWS_STORAGE_BUCKET_NAME = AWS_STORAGE_BUCKET_NAME_STATIC

    STORAGES = {
        "staticfiles": {
            "BACKEND": "lcshop.storages_backends.StaticStorage",
        },
        "default": {
            "BACKEND": "lcshop.storages_backends.MediaStorage"
            if USE_S3_MEDIA
            else "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "bucket_name": AWS_MEDIA_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
            } if USE_S3_MEDIA else {},
        },
    }

    STATIC_URL = (
        f"https://{AWS_STORAGE_BUCKET_NAME_STATIC}.s3."
        f"{AWS_S3_REGION_NAME}.amazonaws.com/{AWS_LOCATION}/"
    )
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
        "default": {
            "BACKEND": "lcshop.storages_backends.MediaStorage"
            if USE_S3_MEDIA
            else "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "bucket_name": AWS_MEDIA_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
            } if USE_S3_MEDIA else {},
        },
    }

    STATIC_URL = "/static/"

# --- MEDIA ---
if USE_S3_MEDIA:
    MEDIA_URL = (
        f"https://{AWS_MEDIA_BUCKET_NAME}.s3."
        f"{AWS_S3_REGION_NAME}.amazonaws.com/media/"
    )
    MEDIA_ROOT = None
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Safety fallback (helps some edge cases)
DEFAULT_FILE_STORAGE = (
    "lcshop.storages_backends.MediaStorage"
    if USE_S3_MEDIA
    else "django.core.files.storage.FileSystemStorage"
)


# --- Messages ---
MESSAGE_TAGS = {
    messages.ERROR: "danger",
}

# ==============================
# EMAIL (make deploy-safe)
# ==============================

EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="no-reply@lcshop.local")
