"""
Django settings for lcshop project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from django.contrib.messages import constants as messages
from pathlib import Path
import socket
import os
from decouple import config



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG',cast=bool, default = False)



ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,.elasticbeanstalk.com,.amazonaws.com,.compute.internal"
).split(",")

fqdn = socket.gethostname()
short = fqdn.split(".")[0]

for h in (fqdn, short):
    if h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(h)

try:
    private_ip = socket.gethostbyname(socket.gethostname())
    if private_ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(private_ip)
except Exception:
    pass


# CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = [
    "https://*.elasticbeanstalk.com",
]

# PROXY / HTTPS 
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'admin_honeypot',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'category',
    'accounts',
    'store',
    'carts',
    'orders',
    'storages',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_EXPIRE_SECONDS = 3600
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = 'login'



ROOT_URLCONF = 'lcshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'category.context_processors.category_items',
                'carts.context_processor.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'lcshop.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==============================
# STATIC & MEDIA FILES (S3)
# ==============================

AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-west-2")

# Static bucket (already working)
AWS_STORAGE_BUCKET_NAME_STATIC = config("AWS_STORAGE_BUCKET_NAME_STATIC", default="")

# Media bucket (uploads)
AWS_MEDIA_BUCKET_NAME = config("AWS_MEDIA_BUCKET_NAME", default="lcshop-media-prod")

USE_S3_STATIC = bool(AWS_STORAGE_BUCKET_NAME_STATIC.strip())
USE_S3_MEDIA = bool(AWS_MEDIA_BUCKET_NAME.strip())

AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {}

# Local static setup (for dev)
STATICFILES_DIRS = [
    BASE_DIR / "lcshop" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


# ------------------------------
# STORAGES
# ------------------------------
if USE_S3_STATIC:
    AWS_LOCATION = "static"

    STORAGES = {
        "staticfiles": {
            "BACKEND": "lcshop.storages_backends.StaticStorage",
        },
        "default": {
            "BACKEND": "lcshop.storages_backends.MediaStorage"
            if USE_S3_MEDIA
            else "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "bucket_name": AWS_MEDIA_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
            } if USE_S3_MEDIA else {},
        },
    }

    STATIC_URL = (
        f"https://{AWS_STORAGE_BUCKET_NAME_STATIC}.s3."
        f"{AWS_S3_REGION_NAME}.amazonaws.com/{AWS_LOCATION}/"
    )

else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
        "default": {
            "BACKEND": "lcshop.storages_backends.MediaStorage"
            if USE_S3_MEDIA
            else "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "bucket_name": AWS_MEDIA_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
            } if USE_S3_MEDIA else {},
        },
    }

    STATIC_URL = "/static/"


# ------------------------------
# MEDIA
# ------------------------------
if USE_S3_MEDIA:
    MEDIA_URL = (
        f"https://{AWS_MEDIA_BUCKET_NAME}.s3."
        f"{AWS_S3_REGION_NAME}.amazonaws.com/media/"
    )
    MEDIA_ROOT = None
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"


# Safety fallback (helps Django 5.x edge cases)
DEFAULT_FILE_STORAGE = (
    "lcshop.storages_backends.MediaStorage"
    if USE_S3_MEDIA
    else "django.core.files.storage.FileSystemStorage"
)





# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


MESSAGE_TAGS = {
    messages.ERROR: "danger",

}

#smtp configuration




EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@lcshop.local')
